name: runner1
on: 
  workflow_call:
env:
  SHA: ${{ GITHUB.SHA }}
  REF: ${{ GITHUB.REF }}
  RUN_ID: ${{ GITHUB.RUN_ID }}
  RUN_NUMBER: ${{ GITHUB.RUN_NUMBER }}
  BUILD_RUN_NUMBER: build.${{ GITHUB.RUN_NUMBER }}
  GITHUB_TOKEN: ${{ SECRETS.GITHUB_TOKEN }}
  MYGET_API_TOKEN: ${{ SECRETS.MYGET_API_TOKEN }}
  NUGET_API_TOKEN: ${{ SECRETS.NUGET_API_KEY }}
  COVERALLS_REPO_TOKEN: ${{ SECRETS.COVERALLS_REPO_TOKEN }}
jobs:
  runner 1-1:
    runs-on: windows-lastest
    steps: 
      name: Output Environment Variables
      run: |
        echo "SHA: $GITHUB.SHA"
        echo "REF: $GITHUB.REF"